/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-05 20:10:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688514503258L));
    _jspx_dependants.put("jar:file:/C:/Users/britt/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/kyncl_mod9/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425996670000L));
    _jspx_dependants.put("jar:file:/C:/Users/britt/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/kyncl_mod9/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/x.tld", Long.valueOf(1425996670000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar_005fdoc_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar_005fdoc_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar_005fdoc_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.release();
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005fchoose.release();
    _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.release();
    _005fjspx_005ftagPool_005fx_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Parsing employees.xml</title>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_x_005fparse_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"left\">\r\n");
      out.write("		<h2>Displaying All Employees</h2>\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th colspan=\"4\">All Employees in 'employees.xml' File</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				 <th>Name</th>\r\n");
      out.write("				 <th>Job Title</th>\r\n");
      out.write("				 <th>Department</th>\r\n");
      out.write("				 <th>Salary</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
      if (_jspx_meth_x_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"right\">\r\n");
      out.write("		<h2>Applying Conditional Logic with JSTL Functions to Display XML Data</h2>\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("		    <tr>\r\n");
      out.write("		        <th colspan=\"4\">Employees Salary >50000 in Green or Else in Red</th>\r\n");
      out.write("		    </tr>\r\n");
      out.write("		    <tr>\r\n");
      out.write("		        <th>Name</th>\r\n");
      out.write("		        <th>Job Title</th>\r\n");
      out.write("		        <th>Department</th>\r\n");
      out.write("		        <th>Salary</th>\r\n");
      out.write("		    </tr>\r\n");
      out.write("		    ");
      if (_jspx_meth_x_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	    <br>\r\n");
      out.write("	    <table border=\"1\">\r\n");
      out.write("		    <tr>\r\n");
      out.write("		        <th colspan=\"4\">Employees with Department = 'Engineering'</th>\r\n");
      out.write("		    </tr>\r\n");
      out.write("		    <tr>\r\n");
      out.write("		        <th>Name</th>\r\n");
      out.write("		        <th>Job Title</th>\r\n");
      out.write("		        <th>Department</th>\r\n");
      out.write("		        <th>Salary</th>\r\n");
      out.write("		    </tr>\r\n");
      out.write("		    ");
      if (_jspx_meth_x_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("		    <tr>\r\n");
      out.write("		        <th colspan=\"4\">Employees with Department = 'Finance' or 'Marketing'</th>\r\n");
      out.write("		    </tr>\r\n");
      out.write("		    <tr>\r\n");
      out.write("		        <th>Name</th>\r\n");
      out.write("		        <th>Job Title</th>\r\n");
      out.write("		        <th>Department</th>\r\n");
      out.write("		        <th>Salary</th>\r\n");
      out.write("		    </tr>\r\n");
      out.write("		    ");
      if (_jspx_meth_x_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /index.jsp(22,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("employees.xml");
      // /index.jsp(22,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setVar("employeeData");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fparse_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:parse
    org.apache.taglibs.standard.tag.rt.xml.ParseTag _jspx_th_x_005fparse_005f0 = (org.apache.taglibs.standard.tag.rt.xml.ParseTag) _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar_005fdoc_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ParseTag.class);
    boolean _jspx_th_x_005fparse_005f0_reused = false;
    try {
      _jspx_th_x_005fparse_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fparse_005f0.setParent(null);
      // /index.jsp(23,1) name = doc type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fparse_005f0.setDoc((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeData}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /index.jsp(23,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fparse_005f0.setVar("dom");
      int _jspx_eval_x_005fparse_005f0 = _jspx_th_x_005fparse_005f0.doStartTag();
      if (_jspx_th_x_005fparse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fparse_0026_005fvar_005fdoc_005fnobody.reuse(_jspx_th_x_005fparse_005f0);
      _jspx_th_x_005fparse_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fparse_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fparse_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:forEach
    org.apache.taglibs.standard.tag.common.xml.ForEachTag _jspx_th_x_005fforEach_005f0 = (org.apache.taglibs.standard.tag.common.xml.ForEachTag) _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.get(org.apache.taglibs.standard.tag.common.xml.ForEachTag.class);
    boolean _jspx_th_x_005fforEach_005f0_reused = false;
    try {
      _jspx_th_x_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fforEach_005f0.setParent(null);
      // /index.jsp(37,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f0.setVar("employee");
      // /index.jsp(37,3) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f0.setSelect("$dom/employees/employee");
      int[] _jspx_push_body_count_x_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_x_005fforEach_005f0 = _jspx_th_x_005fforEach_005f0.doStartTag();
        if (_jspx_eval_x_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			");
            out.write("\r\n");
            out.write("			<tr>\r\n");
            out.write("			  	<td>");
            if (_jspx_meth_x_005fout_005f0(_jspx_th_x_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("				<td>");
            if (_jspx_meth_x_005fout_005f1(_jspx_th_x_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("				<td>");
            if (_jspx_meth_x_005fout_005f2(_jspx_th_x_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("				<td>");
            if (_jspx_meth_x_005fout_005f3(_jspx_th_x_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_x_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_x_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_x_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_x_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_x_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.reuse(_jspx_th_x_005fforEach_005f0);
      _jspx_th_x_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f0_reused = false;
    try {
      _jspx_th_x_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f0);
      // /index.jsp(40,10) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f0.setSelect("$employee/name");
      int _jspx_eval_x_005fout_005f0 = _jspx_th_x_005fout_005f0.doStartTag();
      if (_jspx_th_x_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f0);
      _jspx_th_x_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f1_reused = false;
    try {
      _jspx_th_x_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f0);
      // /index.jsp(41,8) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f1.setSelect("$employee/jobTitle");
      int _jspx_eval_x_005fout_005f1 = _jspx_th_x_005fout_005f1.doStartTag();
      if (_jspx_th_x_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f1);
      _jspx_th_x_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f2_reused = false;
    try {
      _jspx_th_x_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f0);
      // /index.jsp(42,8) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f2.setSelect("$employee/department");
      int _jspx_eval_x_005fout_005f2 = _jspx_th_x_005fout_005f2.doStartTag();
      if (_jspx_th_x_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f2);
      _jspx_th_x_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f3_reused = false;
    try {
      _jspx_th_x_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f0);
      // /index.jsp(43,8) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f3.setSelect("$employee/salary");
      int _jspx_eval_x_005fout_005f3 = _jspx_th_x_005fout_005f3.doStartTag();
      if (_jspx_th_x_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f3);
      _jspx_th_x_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:forEach
    org.apache.taglibs.standard.tag.common.xml.ForEachTag _jspx_th_x_005fforEach_005f1 = (org.apache.taglibs.standard.tag.common.xml.ForEachTag) _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.get(org.apache.taglibs.standard.tag.common.xml.ForEachTag.class);
    boolean _jspx_th_x_005fforEach_005f1_reused = false;
    try {
      _jspx_th_x_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_x_005fforEach_005f1.setParent(null);
      // /index.jsp(59,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f1.setVar("employee");
      // /index.jsp(59,6) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f1.setSelect("$dom/employees/employee");
      int[] _jspx_push_body_count_x_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_x_005fforEach_005f1 = _jspx_th_x_005fforEach_005f1.doStartTag();
        if (_jspx_eval_x_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		        ");
            if (_jspx_meth_x_005fchoose_005f0(_jspx_th_x_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("		    ");
            int evalDoAfterBody = _jspx_th_x_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_x_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_x_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_x_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_x_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.reuse(_jspx_th_x_005fforEach_005f1);
      _jspx_th_x_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_x_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_x_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fx_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_x_005fchoose_005f0_reused = false;
    try {
      _jspx_th_x_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f1);
      int _jspx_eval_x_005fchoose_005f0 = _jspx_th_x_005fchoose_005f0.doStartTag();
      if (_jspx_eval_x_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		        	");
          out.write("\r\n");
          out.write("		            ");
          if (_jspx_meth_x_005fwhen_005f0(_jspx_th_x_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("		            ");
          out.write("\r\n");
          out.write("		            ");
          if (_jspx_meth_x_005fwhen_005f1(_jspx_th_x_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("		            ");
          out.write("\r\n");
          out.write("		            ");
          if (_jspx_meth_x_005fotherwise_005f0(_jspx_th_x_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("		        ");
          int evalDoAfterBody = _jspx_th_x_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fchoose.reuse(_jspx_th_x_005fchoose_005f0);
      _jspx_th_x_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:when
    org.apache.taglibs.standard.tag.common.xml.WhenTag _jspx_th_x_005fwhen_005f0 = (org.apache.taglibs.standard.tag.common.xml.WhenTag) _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.get(org.apache.taglibs.standard.tag.common.xml.WhenTag.class);
    boolean _jspx_th_x_005fwhen_005f0_reused = false;
    try {
      _jspx_th_x_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fchoose_005f0);
      // /index.jsp(62,14) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fwhen_005f0.setSelect("$employee/salary>50000");
      int _jspx_eval_x_005fwhen_005f0 = _jspx_th_x_005fwhen_005f0.doStartTag();
      if (_jspx_eval_x_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		                <tr style=\"background-color: #BDFCB1;\">\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f4(_jspx_th_x_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f5(_jspx_th_x_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f6(_jspx_th_x_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f7(_jspx_th_x_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                </tr>\r\n");
          out.write("		            ");
          int evalDoAfterBody = _jspx_th_x_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.reuse(_jspx_th_x_005fwhen_005f0);
      _jspx_th_x_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f4_reused = false;
    try {
      _jspx_th_x_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f0);
      // /index.jsp(64,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f4.setSelect("$employee/name");
      int _jspx_eval_x_005fout_005f4 = _jspx_th_x_005fout_005f4.doStartTag();
      if (_jspx_th_x_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f4);
      _jspx_th_x_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f5_reused = false;
    try {
      _jspx_th_x_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f0);
      // /index.jsp(65,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f5.setSelect("$employee/jobTitle");
      int _jspx_eval_x_005fout_005f5 = _jspx_th_x_005fout_005f5.doStartTag();
      if (_jspx_th_x_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f5);
      _jspx_th_x_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f6_reused = false;
    try {
      _jspx_th_x_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f0);
      // /index.jsp(66,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f6.setSelect("$employee/department");
      int _jspx_eval_x_005fout_005f6 = _jspx_th_x_005fout_005f6.doStartTag();
      if (_jspx_th_x_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f6);
      _jspx_th_x_005fout_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f6, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f7_reused = false;
    try {
      _jspx_th_x_005fout_005f7.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f0);
      // /index.jsp(67,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f7.setSelect("$employee/salary");
      int _jspx_eval_x_005fout_005f7 = _jspx_th_x_005fout_005f7.doStartTag();
      if (_jspx_th_x_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f7);
      _jspx_th_x_005fout_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f7, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:when
    org.apache.taglibs.standard.tag.common.xml.WhenTag _jspx_th_x_005fwhen_005f1 = (org.apache.taglibs.standard.tag.common.xml.WhenTag) _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.get(org.apache.taglibs.standard.tag.common.xml.WhenTag.class);
    boolean _jspx_th_x_005fwhen_005f1_reused = false;
    try {
      _jspx_th_x_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_x_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fchoose_005f0);
      // /index.jsp(71,14) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fwhen_005f1.setSelect("$employee/salary<=50000");
      int _jspx_eval_x_005fwhen_005f1 = _jspx_th_x_005fwhen_005f1.doStartTag();
      if (_jspx_eval_x_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		                <tr style=\"background-color: #FFC0C0;\">\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f8(_jspx_th_x_005fwhen_005f1, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f9(_jspx_th_x_005fwhen_005f1, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f10(_jspx_th_x_005fwhen_005f1, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f11(_jspx_th_x_005fwhen_005f1, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                </tr>\r\n");
          out.write("		            ");
          int evalDoAfterBody = _jspx_th_x_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.reuse(_jspx_th_x_005fwhen_005f1);
      _jspx_th_x_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_x_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f8_reused = false;
    try {
      _jspx_th_x_005fout_005f8.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f1);
      // /index.jsp(73,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f8.setSelect("$employee/name");
      int _jspx_eval_x_005fout_005f8 = _jspx_th_x_005fout_005f8.doStartTag();
      if (_jspx_th_x_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f8);
      _jspx_th_x_005fout_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f8, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f9 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f9_reused = false;
    try {
      _jspx_th_x_005fout_005f9.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f1);
      // /index.jsp(74,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f9.setSelect("$employee/jobTitle");
      int _jspx_eval_x_005fout_005f9 = _jspx_th_x_005fout_005f9.doStartTag();
      if (_jspx_th_x_005fout_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f9);
      _jspx_th_x_005fout_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f9, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f10 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f10_reused = false;
    try {
      _jspx_th_x_005fout_005f10.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f1);
      // /index.jsp(75,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f10.setSelect("$employee/department");
      int _jspx_eval_x_005fout_005f10 = _jspx_th_x_005fout_005f10.doStartTag();
      if (_jspx_th_x_005fout_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f10);
      _jspx_th_x_005fout_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f10, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f11 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f11_reused = false;
    try {
      _jspx_th_x_005fout_005f11.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f1);
      // /index.jsp(76,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f11.setSelect("$employee/salary");
      int _jspx_eval_x_005fout_005f11 = _jspx_th_x_005fout_005f11.doStartTag();
      if (_jspx_th_x_005fout_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f11);
      _jspx_th_x_005fout_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f11, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_x_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fx_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_x_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_x_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fchoose_005f0);
      int _jspx_eval_x_005fotherwise_005f0 = _jspx_th_x_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_x_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		                <tr>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f12(_jspx_th_x_005fotherwise_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f13(_jspx_th_x_005fotherwise_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f14(_jspx_th_x_005fotherwise_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f15(_jspx_th_x_005fotherwise_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("		                </tr>\r\n");
          out.write("		            ");
          int evalDoAfterBody = _jspx_th_x_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fotherwise.reuse(_jspx_th_x_005fotherwise_005f0);
      _jspx_th_x_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_x_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f12 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f12_reused = false;
    try {
      _jspx_th_x_005fout_005f12.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fotherwise_005f0);
      // /index.jsp(82,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f12.setSelect("$employee/name");
      int _jspx_eval_x_005fout_005f12 = _jspx_th_x_005fout_005f12.doStartTag();
      if (_jspx_th_x_005fout_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f12);
      _jspx_th_x_005fout_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f12, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f13 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f13_reused = false;
    try {
      _jspx_th_x_005fout_005f13.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fotherwise_005f0);
      // /index.jsp(83,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f13.setSelect("$employee/jobTitle");
      int _jspx_eval_x_005fout_005f13 = _jspx_th_x_005fout_005f13.doStartTag();
      if (_jspx_th_x_005fout_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f13);
      _jspx_th_x_005fout_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f13, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f14 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f14_reused = false;
    try {
      _jspx_th_x_005fout_005f14.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fotherwise_005f0);
      // /index.jsp(84,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f14.setSelect("$employee/department");
      int _jspx_eval_x_005fout_005f14 = _jspx_th_x_005fout_005f14.doStartTag();
      if (_jspx_th_x_005fout_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f14);
      _jspx_th_x_005fout_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f14, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f15(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f15 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f15_reused = false;
    try {
      _jspx_th_x_005fout_005f15.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f15.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fotherwise_005f0);
      // /index.jsp(85,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f15.setSelect("$employee/salary");
      int _jspx_eval_x_005fout_005f15 = _jspx_th_x_005fout_005f15.doStartTag();
      if (_jspx_th_x_005fout_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f15);
      _jspx_th_x_005fout_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f15, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:forEach
    org.apache.taglibs.standard.tag.common.xml.ForEachTag _jspx_th_x_005fforEach_005f2 = (org.apache.taglibs.standard.tag.common.xml.ForEachTag) _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.get(org.apache.taglibs.standard.tag.common.xml.ForEachTag.class);
    boolean _jspx_th_x_005fforEach_005f2_reused = false;
    try {
      _jspx_th_x_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_x_005fforEach_005f2.setParent(null);
      // /index.jsp(102,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f2.setVar("employee");
      // /index.jsp(102,6) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f2.setSelect("$dom/employees/employee");
      int[] _jspx_push_body_count_x_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_x_005fforEach_005f2 = _jspx_th_x_005fforEach_005f2.doStartTag();
        if (_jspx_eval_x_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		        ");
            if (_jspx_meth_x_005fchoose_005f1(_jspx_th_x_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("		    ");
            int evalDoAfterBody = _jspx_th_x_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_x_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_x_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_x_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_x_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.reuse(_jspx_th_x_005fforEach_005f2);
      _jspx_th_x_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_x_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_x_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fx_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_x_005fchoose_005f1_reused = false;
    try {
      _jspx_th_x_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_x_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f2);
      int _jspx_eval_x_005fchoose_005f1 = _jspx_th_x_005fchoose_005f1.doStartTag();
      if (_jspx_eval_x_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		        	");
          out.write("\r\n");
          out.write("		            ");
          if (_jspx_meth_x_005fwhen_005f2(_jspx_th_x_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f2))
            return true;
          out.write("\r\n");
          out.write("		        ");
          int evalDoAfterBody = _jspx_th_x_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fchoose.reuse(_jspx_th_x_005fchoose_005f1);
      _jspx_th_x_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_x_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:when
    org.apache.taglibs.standard.tag.common.xml.WhenTag _jspx_th_x_005fwhen_005f2 = (org.apache.taglibs.standard.tag.common.xml.WhenTag) _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.get(org.apache.taglibs.standard.tag.common.xml.WhenTag.class);
    boolean _jspx_th_x_005fwhen_005f2_reused = false;
    try {
      _jspx_th_x_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_x_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fchoose_005f1);
      // /index.jsp(105,14) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fwhen_005f2.setSelect("$employee/department='Engineering'");
      int _jspx_eval_x_005fwhen_005f2 = _jspx_th_x_005fwhen_005f2.doStartTag();
      if (_jspx_eval_x_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		                <tr>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f16(_jspx_th_x_005fwhen_005f2, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f2))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f17(_jspx_th_x_005fwhen_005f2, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f2))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f18(_jspx_th_x_005fwhen_005f2, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f2))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f19(_jspx_th_x_005fwhen_005f2, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f2))
            return true;
          out.write("</td>\r\n");
          out.write("		                </tr>\r\n");
          out.write("		            ");
          int evalDoAfterBody = _jspx_th_x_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.reuse(_jspx_th_x_005fwhen_005f2);
      _jspx_th_x_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_x_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f16(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f16 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f16_reused = false;
    try {
      _jspx_th_x_005fout_005f16.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f16.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f2);
      // /index.jsp(107,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f16.setSelect("$employee/name");
      int _jspx_eval_x_005fout_005f16 = _jspx_th_x_005fout_005f16.doStartTag();
      if (_jspx_th_x_005fout_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f16);
      _jspx_th_x_005fout_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f16, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f16_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f17(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f17 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f17_reused = false;
    try {
      _jspx_th_x_005fout_005f17.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f17.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f2);
      // /index.jsp(108,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f17.setSelect("$employee/jobTitle");
      int _jspx_eval_x_005fout_005f17 = _jspx_th_x_005fout_005f17.doStartTag();
      if (_jspx_th_x_005fout_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f17);
      _jspx_th_x_005fout_005f17_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f17, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f17_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f18(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f18 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f18_reused = false;
    try {
      _jspx_th_x_005fout_005f18.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f18.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f2);
      // /index.jsp(109,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f18.setSelect("$employee/department");
      int _jspx_eval_x_005fout_005f18 = _jspx_th_x_005fout_005f18.doStartTag();
      if (_jspx_th_x_005fout_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f18);
      _jspx_th_x_005fout_005f18_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f18, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f18_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f19(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f19 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f19_reused = false;
    try {
      _jspx_th_x_005fout_005f19.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f19.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f2);
      // /index.jsp(110,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f19.setSelect("$employee/salary");
      int _jspx_eval_x_005fout_005f19 = _jspx_th_x_005fout_005f19.doStartTag();
      if (_jspx_th_x_005fout_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f19);
      _jspx_th_x_005fout_005f19_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f19, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f19_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:forEach
    org.apache.taglibs.standard.tag.common.xml.ForEachTag _jspx_th_x_005fforEach_005f3 = (org.apache.taglibs.standard.tag.common.xml.ForEachTag) _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.get(org.apache.taglibs.standard.tag.common.xml.ForEachTag.class);
    boolean _jspx_th_x_005fforEach_005f3_reused = false;
    try {
      _jspx_th_x_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_x_005fforEach_005f3.setParent(null);
      // /index.jsp(127,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f3.setVar("employee");
      // /index.jsp(127,6) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fforEach_005f3.setSelect("$dom/employees/employee");
      int[] _jspx_push_body_count_x_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_x_005fforEach_005f3 = _jspx_th_x_005fforEach_005f3.doStartTag();
        if (_jspx_eval_x_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		        ");
            if (_jspx_meth_x_005fchoose_005f2(_jspx_th_x_005fforEach_005f3, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f3))
              return true;
            out.write("\r\n");
            out.write("		    ");
            int evalDoAfterBody = _jspx_th_x_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_x_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_x_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_x_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_x_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.reuse(_jspx_th_x_005fforEach_005f3);
      _jspx_th_x_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_x_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fchoose_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_x_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fx_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_x_005fchoose_005f2_reused = false;
    try {
      _jspx_th_x_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_x_005fchoose_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f3);
      int _jspx_eval_x_005fchoose_005f2 = _jspx_th_x_005fchoose_005f2.doStartTag();
      if (_jspx_eval_x_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		        	");
          out.write("\r\n");
          out.write("		            ");
          if (_jspx_meth_x_005fwhen_005f3(_jspx_th_x_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f3))
            return true;
          out.write("\r\n");
          out.write("		        ");
          int evalDoAfterBody = _jspx_th_x_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fchoose.reuse(_jspx_th_x_005fchoose_005f2);
      _jspx_th_x_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_x_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:when
    org.apache.taglibs.standard.tag.common.xml.WhenTag _jspx_th_x_005fwhen_005f3 = (org.apache.taglibs.standard.tag.common.xml.WhenTag) _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.get(org.apache.taglibs.standard.tag.common.xml.WhenTag.class);
    boolean _jspx_th_x_005fwhen_005f3_reused = false;
    try {
      _jspx_th_x_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_x_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fchoose_005f2);
      // /index.jsp(130,14) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fwhen_005f3.setSelect("$employee/department='Finance' or $employee/department='Marketing'");
      int _jspx_eval_x_005fwhen_005f3 = _jspx_th_x_005fwhen_005f3.doStartTag();
      if (_jspx_eval_x_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		                <tr>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f20(_jspx_th_x_005fwhen_005f3, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f3))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f21(_jspx_th_x_005fwhen_005f3, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f3))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f22(_jspx_th_x_005fwhen_005f3, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f3))
            return true;
          out.write("</td>\r\n");
          out.write("		                    <td>");
          if (_jspx_meth_x_005fout_005f23(_jspx_th_x_005fwhen_005f3, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f3))
            return true;
          out.write("</td>\r\n");
          out.write("		                </tr>\r\n");
          out.write("		            ");
          int evalDoAfterBody = _jspx_th_x_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fwhen_0026_005fselect.reuse(_jspx_th_x_005fwhen_005f3);
      _jspx_th_x_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_x_005fwhen_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f20(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f20 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f20_reused = false;
    try {
      _jspx_th_x_005fout_005f20.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f20.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f3);
      // /index.jsp(132,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f20.setSelect("$employee/name");
      int _jspx_eval_x_005fout_005f20 = _jspx_th_x_005fout_005f20.doStartTag();
      if (_jspx_th_x_005fout_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f20);
      _jspx_th_x_005fout_005f20_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f20, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f20_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f21(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f21 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f21_reused = false;
    try {
      _jspx_th_x_005fout_005f21.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f21.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f3);
      // /index.jsp(133,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f21.setSelect("$employee/jobTitle");
      int _jspx_eval_x_005fout_005f21 = _jspx_th_x_005fout_005f21.doStartTag();
      if (_jspx_th_x_005fout_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f21);
      _jspx_th_x_005fout_005f21_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f21, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f21_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f22(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f22 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f22_reused = false;
    try {
      _jspx_th_x_005fout_005f22.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f22.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f3);
      // /index.jsp(134,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f22.setSelect("$employee/department");
      int _jspx_eval_x_005fout_005f22 = _jspx_th_x_005fout_005f22.doStartTag();
      if (_jspx_th_x_005fout_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f22);
      _jspx_th_x_005fout_005f22_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f22, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f22_reused);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f23(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fwhen_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f23 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    boolean _jspx_th_x_005fout_005f23_reused = false;
    try {
      _jspx_th_x_005fout_005f23.setPageContext(_jspx_page_context);
      _jspx_th_x_005fout_005f23.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fwhen_005f3);
      // /index.jsp(135,26) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005fout_005f23.setSelect("$employee/salary");
      int _jspx_eval_x_005fout_005f23 = _jspx_th_x_005fout_005f23.doStartTag();
      if (_jspx_th_x_005fout_005f23.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f23);
      _jspx_th_x_005fout_005f23_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_x_005fout_005f23, _jsp_getInstanceManager(), _jspx_th_x_005fout_005f23_reused);
    }
    return false;
  }
}
