/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-11 20:46:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bkyncl_mod2.jsp.FunUtils;
import java.util.*;
import java.io.*;
import java.sql.*;
import com.bkyncl_mod2.jsp.FunUtils;

public final class cookie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bkyncl_mod2.jsp.FunUtils");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Cookie Customization Example</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "my-header.html", out, false);
      out.write("\r\n");
      out.write("	<h2>Example Heading: Phrase</h2>\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li>List Item</li>\r\n");
      out.write("		<li>List Item</li>\r\n");
      out.write("		<li>List Item</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<form action=\"cookie.jsp\" method=\"post\">\r\n");
      out.write("		<label>Select your favorite color: </label>\r\n");
      out.write("		<select name=\"favoritecolor\">\r\n");
      out.write("			<option value=\"red\">Red</option>\r\n");
      out.write("			<option value=\"blue\">Blue</option>\r\n");
      out.write("			<option value=\"green\"> Green</option>\r\n");
      out.write("		</select><br>\r\n");
      out.write("		<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("	<form action=\"cookie.jsp\">\r\n");
      out.write("		<label>Select your favorite language: </label>\r\n");
      out.write("		<select name=\"favoritlang\">\r\n");
      out.write("			<option value=\"Java\">Java</option>\r\n");
      out.write("			<option value=\"C++\">C++</option>\r\n");
      out.write("			<option value=\"Python\"> Python</option>\r\n");
      out.write("		</select><br>\r\n");
      out.write("		<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');

		
		String color = "";
	    if (request.getMethod().equalsIgnoreCase("post")) {
	    	// Retrieve the selected color from the request parameters
	        color = request.getParameter("favoritecolor");
	    	
	      	//crete the cookie which consists of a key value pair (name:value)
			Cookie theCookie = new Cookie("user.color", color);
			
			//set the lifespan of the cookie (total number in seconds)
			theCookie.setMaxAge(60*60*24*365);  //one year
			
			// send cookie to broswer by loading it up into response object that goes back to browser
			response.addCookie(theCookie);
	    	
	    } else {
			String cookieColor = null;
			// store cookies in array
			Cookie[] theCookies = request.getCookies();
			
			if(theCookies != null) {
				for(Cookie tempCookie : theCookies) {
					if("user.color".equals(tempCookie.getName())) {
						cookieColor = tempCookie.getValue();
						break;
					}
				}
			}
	        color = cookieColor;
	    }
	    
	    out.println("<br>" + color);
	
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("		 // Set the background color of the body using the selected color\r\n");
      out.write("		 document.body.style.backgroundColor = '");
      out.print( color );
      out.write("';\r\n");
      out.write("    </script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<form method=\"get\" action=\"index.jsp\">\r\n");
      out.write("		<button type=\"submit\">Return to Home</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<form method=\"get\" action=\"extended.jsp\">\r\n");
      out.write("		<button type=\"submit\">To Example Page</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "my-footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
