/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-11 20:46:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bkyncl_mod2.jsp.FunUtils;
import java.util.*;
import java.io.*;
import java.sql.*;
import com.bkyncl_mod2.jsp.FunUtils;

public final class extended_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


			String makeItLower(String words) {
				return words.toLowerCase();
			}
		
 String words = "Hello World"; 
			String words2 = "goodbye world";
		
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bkyncl_mod2.jsp.FunUtils");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"ISO-8859-1\">\r\n");
      out.write("	<title>JSP Demo Expanded Part Two</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "my-header.html", out, false);
      out.write("\r\n");
      out.write("	<h2>JSP Practice Examples Continued...</h2>\r\n");
      out.write("	\r\n");
      out.write("	<p>The time on the server is ");
      out.print( new java.util.Date());
      out.write("</p>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<p>JSP Expression Examples:<br>\r\n");
      out.write("		Converting a string to upper case: ");
      out.print( new String("hello world").toUpperCase() );
      out.write(" <br>\r\n");
      out.write("		25 multiplied by 4 = ");
      out.print( 25*4 );
      out.write(" <br>\r\n");
      out.write("		Is 75 less than 69? ");
      out.print( 75 < 69 );
      out.write(" <br>\r\n");
      out.write("	</p>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<p>JSP Scriptlet Examples:<br>\r\n");
      out.write("		Hello World! Using for loop to print X 5...<br>\r\n");
      out.write("		");

			for(int i=0; i<5; i++) {
				out.println("Hello again! i : " + i + "<br>");
			}
		
      out.write("\r\n");
      out.write("		<br>\r\n");
      out.write("	</p>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<p>JSP Declaration Examples:<br>\r\n");
      out.write("		Using a JSP method declaration to convert a string to lower case<br>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		Convert ");
 out.println(words); 
      out.write(" to lower = ");
      out.print( makeItLower(words) );
      out.write(" <br>\r\n");
      out.write("		\r\n");
      out.write("	</p>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<p>Calling a Java Class from JSP example:<br>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		Convert ");
 out.println(words); 
      out.write(" to upper = ");
      out.print( com.bkyncl_mod2.jsp.FunUtils.makeItUpper(words) );
      out.write(" <br>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		Convert ");
 out.println(words2); 
      out.write(" to upper = ");
      out.print( FunUtils.makeItUpper(words2) );
      out.write(" <br>\r\n");
      out.write("		\r\n");
      out.write("	</p>\r\n");
      out.write("	\r\n");
      out.write("	<h2>Practice with JSP Objects...</h2>\r\n");
      out.write("	<p>Commonly used JSP objects..</p>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>Request: Contains information about the HTTP request headers and form data</li>\r\n");
      out.write("			<li>Response: Provides HTTP support for sending response</li>\r\n");
      out.write("			<li>Out: JspWriter for including content in HTML page \"out.prinln()\"</li>\r\n");
      out.write("			<li>Session: Unique session for each user of the web application</li>\r\n");
      out.write("			<li>Application: Shared data for all users of the web application</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	<p>Request user agent: ");
      out.print( request.getHeader("User-Agent") );
      out.write(" <br>\r\n");
      out.write("		Request user agent language: ");
      out.print( request.getLocale() );
      out.write(" <br>\r\n");
      out.write("	</p>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<h2>Handling HTML forms with JSP...</h2>\r\n");
      out.write("	<form action=\"extended.jsp\" method=\"post\">\r\n");
      out.write("		<label>First name: </label>\r\n");
      out.write("		<input type=\"text\" name=\"firstname\" /><br>\r\n");
      out.write("		<label>Last name: </label>\r\n");
      out.write("		<input type=\"text\" name=\"lastname\" /><br>\r\n");
      out.write("		<label>Language: </label>\r\n");
      out.write("		<input type=\"radio\" name=\"lang\" value=\"English\"/>English\r\n");
      out.write("		<input type=\"radio\" name=\"lang\" value=\"Spanish\"/>Spanish\r\n");
      out.write("		<input type=\"radio\" name=\"lang\" value=\"French\"/>French<br>\r\n");
      out.write("		<label>Favorite Colors: </label>\r\n");
      out.write("		<input type=\"checkbox\" name=\"color\" value=\"Blue\"/>Blue\r\n");
      out.write("		<input type=\"checkbox\" name=\"color\" value=\"Red\"/>Red\r\n");
      out.write("		<input type=\"checkbox\" name=\"color\" value=\"Green\"/>Green<br>\r\n");
      out.write("		<label>Major: </label>\r\n");
      out.write("		<select name=\"major\">\r\n");
      out.write("			<option>Business</option>\r\n");
      out.write("			<option>Science</option>\r\n");
      out.write("			<option>English</option>\r\n");
      out.write("			<option>Arts</option>\r\n");
      out.write("		</select><br>\r\n");
      out.write("		<input type=\"submit\" value=\"Submit\" />\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 out.println("Student Name: " + request.getParameter("firstname") + " " + request.getParameter("lastname")); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 out.println("<br>Student Major:" + request.getParameter("major")); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 out.println("<br>Student Language:" + request.getParameter("lang")); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 
		String[] colors;
		if(request.getParameterValues("color") != null) {
			colors = request.getParameterValues("color");
		} else {
			colors = new String[]{"red", "blue", "green"};
		}
		out.println("<br>Student colors: ");
		for (String color : colors ) {
			out.println("<li>" + color + "</li>");
		}
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<p>Student Name: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.firstname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.lastname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("		Student Major: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.major}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("		Student Language: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.lang}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("		Student Colors: \r\n");
      out.write("		");

		for (String color : colors ) {
			out.println("<li>" + color + "</li>");
		}
		
      out.write("\r\n");
      out.write("	</p>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');

		// read sutdent language from form data
		String studentlang;
		if( request.getParameter("lang") != null){
			studentlang = request.getParameter("lang");
		} else {
			studentlang = "english";
		}
		studentlang = studentlang.trim(); // Trim leading and trailing spaces
		
		//crete the cookie which consists of a key value pair (name:value)
		Cookie theCookie = new Cookie("student.lang", studentlang);
		
		//set the lifespan of the cookie (total number in seconds)
		theCookie.setMaxAge(60*60*24*365);  //one year
		
		// send cookie to broswer by loading it up into response object that goes back to browser
		response.addCookie(theCookie);
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');

		String cookieLang = null;
		Cookie[] theCookies = request.getCookies();
		
		if(theCookies != null) {
			for(Cookie tempCookie : theCookies) {
				if("student.lang".equals(tempCookie.getName())) {
					cookieLang = tempCookie.getValue();
					break;
				}
			}
		}
		out.println("student language cookie value: " + cookieLang);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<p>In this example we have used the inclusion of external files to display both the header and footer</p>\r\n");
      out.write("	\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<form method=\"get\" action=\"index.jsp\">\r\n");
      out.write("		<button type=\"submit\">Return to Home</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<form method=\"get\" action=\"cookie.jsp\">\r\n");
      out.write("		<button type=\"submit\">To Cookie Page</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "my-footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
